Refactor: Use util_diff to store common pieces of code, including a leftover check for followup

diff --git a/scripts/cmd_followup.in b/scripts/cmd_followup.in
--- a/scripts/cmd_followup.in
+++ b/scripts/cmd_followup.in
@@ -149,6 +149,7 @@ fi
 
 echo "===> Collecting info about PR $PR_NUMBER"
 SUBJECT=`fetch -qo - "http://www.freebsd.org/cgi/query-pr.cgi?pr=${PR_NUMBER}" |sed -E '/title/!d; /head/!d; s/<[^>]*[>]//g'`
+RESPONSIBLE=`fetch -qo - "http://www.freebsd.org/cgi/query-pr.cgi?pr=${PR_NUMBER}" |sed -E '/Responsible/!d; s/<[^>]*[>]/ /g; s/.*Responsible: //g; s/State: .*//' |tr -d " "`
 echo "===> Subject of PR $PR_NUMBER:"
 echo "$SUBJECT"
 
@@ -202,7 +203,7 @@ else
 	fi
 
 	# Set PR parameters based on selected mode
-	DESCRIPTION="[DESCRIBE CHANGES]"
+	DESCRIPTION="[PORTTOOLS: DESCRIBE CHANGES]"
 
 	if [ "${MODE}" = "update" ]
 	then
@@ -241,6 +242,12 @@ else
 	fi
 fi
 
+if [ "x${RESPONSIBLE}" != "x" -a "${MAINTAINER}" != "${RESPONSIBLE}@FreeBSD.org" ]; then
+	CC="${CC}; ${RESPONSIBLE}@freebsd.org"
+elif [ "x${RESPONSIBLE}" != "x" ]; then
+	CC="${CC}"
+fi
+
 BOUNDARY=`date|md5sum`
 
 echo "===> Generating Followup form"
@@ -256,13 +263,12 @@ cat > ${PR_FORM} <<- EOF
 	Content-Type: multipart/mixed; boundary="------${BOUNDARY}"
 
 
-	This is a multi-part message in MIME format.
 	--------${BOUNDARY}
 	Content-Type: text/plain; charset=utf-8; format=flowed
 	Content-Transfer-Encoding: 8bit
 
 
-	[DESCRIBE CHANGES]
+	Description:
 EOF
 
 MODESTRING="mode: ${MODE}"
@@ -298,19 +304,16 @@ else
 	if [ "${CC}" != "" ]
 	then
 		echo >> ${PR_FORM}
-		echo "Port maintainer (${CC}) is cc'd." >> ${PR_FORM}
+		if [ "x${RESPONSIBLE}" != "x" -a "${MAINTAINER}" != "${RESPONSIBLE}@FreeBSD.org" ]; then
+			echo "Port maintainer and responsible committer (${CC}) are cc'd." >> ${PR_FORM}
+		else
+			echo "Port maintainer (${CC}) is cc'd." >> ${PR_FORM}
+		fi
 	fi
 fi
-
 if [ "${COMMITTER}" = "yes" ]
 then
-	echo "" >> ${PR_FORM}
-	echo "<Handy template to provide proof of cleanliness>" >> ${PR_FORM}
-	echo -n "portlint: " >> ${PR_FORM}
-	cat ${PORTLINT_LOG} >> ${PR_FORM}
-	echo "port test: " >> ${PR_FORM}
-	echo "testport: " >> ${PR_FORM}
-	echo "redports: " >> ${PR_FORM}
+	build_template
 fi
 
 cat >> ${PR_FORM} <<- EOF
@@ -337,6 +340,11 @@ Content-Disposition: attachment;
 
 EOF
 
+else
+	echo "Could not append patch"
+	cleanup
+	exit 1
+
 fi;
 
 
@@ -351,14 +359,16 @@ ${EDITOR} ${PR_FORM}
 
 		case "$input" in
 		a*)
-		   cleanup
-		   exit
-		   ;;
+			cleanup
+			exit
+			;;
 		e*)
-		   ${EDITOR} ${PR_FORM}
-		   continue 2
-		   ;;
+			${EDITOR} ${PR_FORM}
+			continue 2
+			;;
 		s*)
+			# Check for leftovers
+			leftover_check ${PR_FORM}
 			echo "===> Invoking sendmail(8) to submit a PR"
 			cat "${PR_FORM}" "${PATCH}.att" | /usr/sbin/sendmail -t -F "${FULLNAME}" -f "${EMAIL}"
 			break 2
diff --git a/scripts/util_diff.in b/scripts/util_diff.in
--- a/scripts/util_diff.in
+++ b/scripts/util_diff.in
@@ -26,6 +26,28 @@ cleanup ()
 	echo "====> Cleaning up"
 	rm -rf ${TEMPROOT}
 }
+build_template ()
+{
+	echo "" >> ${PR_FORM}
+	echo "[PORTTOOLS: Handy template]" >> ${PR_FORM}
+	echo -n "portlint: " >> ${PR_FORM}
+	if [ "${RUN_PORTLINT}" = "yes"]; then
+		cat ${PORTLINT_LOG} >> ${PR_FORM}
+	else
+		echo "ok" >> ${PR_FORM}
+	fi
+	echo "port test: " >> ${PR_FORM}
+	echo "testport: " >> ${PR_FORM}
+	echo "redports: " >> ${PR_FORM}
+}
+
+leftover_check ()
+{
+	echo "===> Checking for leftovers"
+	grep "\[PORTTOOLS:" $PR_FORM  >/dev/null && LEFTOVERS="1" || LEFTOVERS="0"
+	[ "${LEFTOVERS}" == "1" ] && echo "Found leftovers. Aborting submission..." && cleanup && exit 1 || echo "No leftovers, proceeding...."
+}
+
 
 if [ "${MODE}" = "new" ]
 then
@@ -85,7 +107,7 @@ else
 		fi
 	elif [ "${DIFF_MODE}" = "GIT" ]
 	then
-		# If `pwd` is not a svn working copy
+		# If `pwd` is not a git working copy
 		# fallback to diffing against ${PORTSDIR} tree
 		git status > /dev/null 2>&1
 		status=$?
